<?php

namespace AppBundle\Repository;

/**
 * CarServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
