<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Get all exists categories
     *
     * @return array
     */
    public function getAllCategory()
    {
        $query = $this->createQueryBuilder('c')
            ->getQuery();

        return $query->getResult();
    }


    /**
     * Get category by name
     *
     * @param $name
     * @return \AppBundle\Entity\Category|null|object
     */
    public function getCategoryByName($name)
    {
        $product = $this->getEntityManager()
            ->getRepository('AppBundle:Category')
            ->findOneBy(['name' => $name]);

        return $product;
    }
}
