<?php

namespace AppBundle\Repository;

/**
 * OffersCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffersCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get category list
     *
     * Get category list sorted by name
     *
     * @return array
     */
    public function getCategoryList()
    {
        $query = $this->createQueryBuilder('c')
            ->orderBy('c.name', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

    /**
     * Get item by name
     *
     * Get offers category item by passed name params
     *
     * @param string $name
     * @return mixed
     */
    public function getItemByName(string $name)
    {
        $query = $this->createQueryBuilder('offers_category')
            ->where('offers_category.name =:name')
            ->setParameter('name', $name)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    /**
     * Get category by slug
     *
     * Get offer category item by passed slug param
     *
     * @param string $slug
     * @return mixed
     */
    public function getCategoryBySlug(string $slug)
    {
        $query = $this->createQueryBuilder('offers_category')
            ->where('offers_category.slug =:slug')
            ->setParameter('slug', $slug)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
