<?php

namespace AppBundle\Repository;

/**
 * OffersCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffersCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get category list
     *
     * Get category list sorted by name
     *
     * @return array
     */
    public function getCategoryList()
    {
        $query = $this->createQueryBuilder('c')
            ->orderBy('c.name', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
