<?php

namespace AppBundle\Repository;

/**
 * OffersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffersRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get offers list
     *
     * Get all offers item list
     *
     * @return array
     */
    public function getOffersList()
    {
        $query = $this->createQueryBuilder('offers')
            ->getQuery();

        return $query->getResult();
    }

    /**
     * Get offers by category
     *
     * Get offers by passed offers category name
     *
     * @param $category string
     * @return array
     */
    public function getOffersByCategory(string $category)
    {
        $query = $this->createQueryBuilder('o')
            ->join('AppBundle:OffersCategory', 'c', 'WITH', 'o.offersCategory = c.id')
            ->where('c.name = :category')
            ->setParameter('category', $category)
            ->getQuery();

//        return $query->getResult();

        return $query;
    }

    public function getOffersCategoryPagination(string $category)
    {
        $em = $this->getEntityManager();

//        $dql = "SELECT o FROM AppBundle:Offers o INNER JOIN AppBundle:OffersCategory c ON o.offersCategory = c.id WHERE c.name = '$category'";
//
//        $query = $em->createQuery($dql);
//
//        return $query;
    }
}
