<?php

namespace AppBundle\Repository;

/**
 * OffersCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffersCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
