<?php

namespace AppBundle\Repository;

/**
 * PrinciplesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrinciplesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get list
     *
     * Get collection of principles
     *
     * @return array
     */
    public function getList()
    {
        $query = $this->createQueryBuilder('principles')
            ->orderBy('principles.id')
            ->getQuery();

        return $query->getResult();
    }
}
