<?php

namespace AppBundle\Repository;

/**
 * PrinciplesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrinciplesRepository extends \Doctrine\ORM\EntityRepository
{
}
