<?php

namespace AppBundle\Repository;

/**
 * PrinciplesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrinciplesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get list
     *
     * Get collection of principles
     *
     * @return array
     */
    public function getList()
    {
        $query = $this->createQueryBuilder('principles')
            ->orderBy('principles.id')
            ->getQuery();

        return $query->getResult();
    }

    /**
     * Get slug by slug
     *
     * Get item principle by passed slug param
     *
     * @param string $slug
     * @return array
     */
    public function getItemBySlug(string $slug)
    {
        $query = $this->createQueryBuilder('principles')
            ->where('principles.slug =:slug')
            ->setParameter('slug', $slug)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
