<?php

namespace AppBundle\Repository;

/**
 * ServiceActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceActionRepository extends \Doctrine\ORM\EntityRepository
{
}
