<?php

namespace AppBundle\Repository;

/**
 * ServiceStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
