<?php

namespace AppBundle\Repository;

/**
 * UserCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCarRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get user car list
     *
     * Get user car by passed user id
     *
     * @param int $userId
     * @return array
     */
    public function getUserCarList(int $userId)
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.user =:user')
            ->setParameter('user', $userId)
            ->getQuery();

        return $query->getResult();
    }

    /**
     * Get user car
     *
     * Get user cat by passed car_id and user_id parameters
     *
     * @param int $carId
     * @param int $userId
     * @return array
     */
    public function getUserCar(int $carId, int $userId)
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.user =:user')
            ->andWhere('c.id =:id')
            ->setParameter('user', $userId)
            ->setParameter('id', $carId)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
