<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find user by user name
     *
     * @param string $username
     * @return mixed
     */
    public function findUserByUsername(string $username)
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.username = :username')
            ->setParameter('username', $username)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    /**
     * Get first user
     *
     * Get the first user item form user list
     *
     * @return mixed
     */
    public function getFirstUser()
    {
        $query = $this->createQueryBuilder('user')
            ->setMaxResults(1)
            ->getQuery();

        return $query->getSingleResult();
    }
}
