<?php

/**
 * Created by PhpStorm.
 * User: kostya
 * Date: 17.10.17
 * Time: 22:24
 */
namespace Tests\UserBundle\Repository;

use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

/**
 * Class UserRepositoryTest
 * @package Tests\UserBundle\Repository
 */
class UserRepositoryTest extends KernelTestCase
{
    /**
     * @var $em EntityManager
     */
    protected $em;

    /**
     * {inheritance}
     */
    protected function setUp()
    {
        self::bootKernel();

        $this->em = static::$kernel->getContainer()
            ->get('doctrine')
            ->getManager();
    }

    /**
     * Test delete user
     */
    public function testDeleteUser()
    {
        $user = $this->em->getRepository('UserBundle:User')->findUserByUsername('test_user_name');

        $this->assertNotEmpty($user);

        $this->assertEquals($user->getUsername(), 'test_user_name');

        $this->em->remove($user);

        $this->em->flush();

        $user = $this->em->getRepository('UserBundle:User')->findUserByUsername('test_user_name');

        $this->isNull($user);

        $this->assertNull($user);
    }

    /**
     * {inheritance}
     */
    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}