<?php

namespace ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarServiceRepository extends EntityRepository
{
    /**
     * Get service list by car id
     *
     * @param int $id
     * @return array
     */
    public function getServiceListByCarId(int $id)
    {
        $query = $this->createQueryBuilder('car_service')
            ->where('car_service.userCar =:id')
            ->setParameter('id', $id)
            ->getQuery();

        return $query->getResult();
    }
}
