user_homepage:
    path:     /index
    defaults: { _controller: UserBundle:User:index }

user_car_home:
    path:     /cars/
    defaults: { _controller: UserBundle:UserCar:index }

user_car_create:
    path:     /cars/create
    defaults: { _controller: UserBundle:UserCar:create }

user_car_edit:
    path:     /cars/edit/{carId}
    defaults: { _controller: UserBundle:UserCar:edit }

user_car_delete:
    path:     /cars/delete/{carId}
    defaults: { _controller: UserBundle:UserCar:delete }

user_car_story:
    path:     /car/story/{carId}
    defaults: { _controller: UserBundle:UserCar:story}