parameters:
    my_user_provider.class: UserBundle\Entity\FOSUserProvider

services:
    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: UserBundle\Form\ProfileFormType
        arguments: ['%fos_user.model.user.class%']
        tags:
            - { name: form.type, alias: app_user_profile}
    app.form.change_password:
        class: UserBundle\Form\ChangePasswordFormType
        arguments: ['%fos_user.model.user.class%']
        tags:
            - { name: form.type, alias: app_user_change_password}

    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ["@fos_user.user_manager", {facebook: facebook_id} ]