services:
    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: UserBundle\Form\ProfileFormType
        arguments: ['%fos_user.model.user.class%']
        tags:
            - { name: form.type, alias: app_user_profile}
    app.form.change_password:
        class: UserBundle\Form\ChangePasswordFormType
        arguments: ['%fos_user.model.user.class%']
        tags:
            - { name: form.type, alias: app_user_change_password}
