index:
    path:     /
    defaults: { _controller: AppBundle:Index:index }

offers_index:
    path:     /offers
    defaults: { _controller: AppBundle:Offers:index }

category_offers_list:
    path:     /offers/{category}
    defaults: { _controller: AppBundle:Offers:categoryOffers }
