index:
    path:     /
    defaults: { _controller: AppBundle:Index:index, breadcrumbs_label: 'Porsche' }

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Index:contact}

question:
    path:     /question
    defaults: { _controller: AppBundle:Question:index}

museum:
    path:     /museum
    defaults: { _controller: AppBundle:Index:museum}

offers_index:
    path:     /offers
    defaults: { _controller: AppBundle:Offers:index, breadcrumbs_label: 'Offers' }

offers_view:
    path:     /offer/{title}
    defaults: { _controller: AppBundle:Offers:view}

category_offers_list:
    path:     /offers/{category}
    defaults: { _controller: AppBundle:Offers:categoryOffers }