parameters:
    request_foundation.class: Symfony\Component\HttpFoundation\Request

services:
    request_redirect_handler:
        class: UserBundle\Handler\RequestRedirectHandler

    app.access_denied_handler:
        class: AppBundle\Security\AccessDeniedHandler
        arguments: ['@request_redirect_handler']

    # Admin offers service
    admin.offers:
        class: AppBundle\Admin\OffersAdmin
        arguments: [~, AppBundle\Entity\Offers, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: AppBundle
              label: 'Offers'
              label_catalogue: 'Offers'

    # Admin offers category service
    admin.offerscategory:
        class: AppBundle\Admin\OffersCategoryAdmin
        arguments: [~, AppBundle\Entity\OffersCategory, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: AppBundle
              label: 'Offers Category'
              label_catalogue: 'Offers Category'

    # Offers category manager
    offers_category_management:
        class: AppBundle\Services\OffersCategoryManager
        arguments: [ '@doctrine.orm.entity_manager' ]

