parameters:
    request_foundation.class: Symfony\Component\HttpFoundation\Request

services:
    request_redirect_handler:
        class: UserBundle\Handler\RequestRedirectHandler

    app.access_denied_handler:
        class: AppBundle\Security\AccessDeniedHandler
        arguments: ['@request_redirect_handler']

    # Admin offers category service
    admin.offerscategory:
        class: AppBundle\Admin\OffersCategoryAdmin
        arguments: [~, AppBundle\Entity\OffersCategory, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: AppBundle
              label: 'Offers Category'
              label_catalogue: 'Offers Category'

    # Admin offers category service
    admin.offers:
        class: AppBundle\Admin\OffersAdmin
        arguments: [~, AppBundle\Entity\Offers, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: AppBundle
              label: 'Offers'
              label_catalogue: 'Offers'

    # User car service
    admin.user_car:
        class: AppBundle\Admin\UserCarAdmin
        arguments: [~, AppBundle\Entity\UserCar, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: AppBundle
              label: 'User car'
              label_catalogue: 'User car'


    # Offers category manager
    offers_category_management:
        class: AppBundle\Services\OffersCategoryManager
        arguments: [ '@doctrine.orm.entity_manager', '@session' ]

    # Register service
    service.regirser_service:
        class: AppBundle\EventListener\ServiceListener
        autowire: true

    # Service status service
    admin.service_status:
        class: AppBundle\Admin\ServiceStatusAdmin
        arguments: [~, AppBundle\Entity\ServiceStatus, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: AppBundle
              label: 'Service status'
              label_catalogue: 'Service status'

    # Service status service
    admin.car_service:
        class: AppBundle\Admin\CarServiceAdmin
        arguments: [~, AppBundle\Entity\CarService, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: AppBundle
              label: 'Car service'
              label_catalogue: 'Car service'

    # Question service
    admin.question:
        class: AppBundle\Admin\QuestionAdmin
        arguments: [~, AppBundle\Entity\Question, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: AppBundle
              label: 'Question'
              label_catalogue: 'Question'


