<?php

namespace CarBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get body data
     *
     * Return body data by car id
     *
     * @param int $id
     * @return mixed
     */
    public function getBodyData(int $id)
    {
        $query = $this->createQueryBuilder('c')
            ->join('CarBundle:Body', 'b', 'WITH', 'c.body = b.id')
            ->where('c.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $query->getSingleResult();
    }
}
