<?php

namespace CarBundle\Repository;

/**
 * DynamicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DynamicsRepository extends \Doctrine\ORM\EntityRepository
{
}
