<?php

namespace CarBundle\Repository;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get models list
     *
     * Get all model list which exists
     *
     * @return mixed
     */
    public function getModelsList()
    {
        $query = $this->createQueryBuilder('m')
            ->orderBy('m.name', 'DESC')
            ->getQuery();

        return $query->execute();
    }

    /**
     * Get Parent model
     *
     * Get Model list which don't have child model
     *
     * @return mixed
     */
    public function getParentModel()
    {
        $query = $this->createQueryBuilder('m')
            ->where('m.parent IS NULL')
            ->getQuery();

        return $query->execute();
    }

    /**
     * Get model by user id
     *
     * Get model list query by passed user id
     *
     * @param $userId
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getModelsByUserId($userId)
    {
        $query = $this->createQueryBuilder('model');

        $userId = ($this->getUserModels($userId)) ? $userId : null;

        $query = ($userId) ? $query
            ->join('UserBundle:UserCar', 'user_car', 'WITH', 'model.id = user_car.model')
            ->where('user_car.user =:userId')
            ->setParameter('userId', $userId) : $query;

        $query->orderBy('model.id', 'ASC');

        return $query;
    }

    /**
     * Get user models
     *
     * Get models collection by passed user id param
     *
     * @param int $userId
     * @return array
     */
    public function getUserModels(int $userId)
    {
        $query = $this->createQueryBuilder('model')
            ->join('model.userCar', 'user_car')
            ->where('user_car.user =:userId')
            ->setParameter('userId', $userId)
            ->getQuery();

        return $query->getResult();
    }

    /**
     * Get model by name
     *
     * Get model item by passed name param
     *
     * @param string $name
     * @return mixed
     */
    public function getModelByName(string $name)
    {
        $query = $this->createQueryBuilder('model')
            ->where('model.name =:name')
            ->setParameter('name', $name)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    /**
     * Search model by name
     *
     * Search model record by passed model name param
     *
     * @param string $name
     * @return array
     */
    public function searchModelByName(string $name)
    {
        $query = $this->createQueryBuilder('model')
            ->leftJoin('model.imageLogo', 'image_logo')
            ->select('model.name', 'model.id', 'model.slug')
            ->addSelect('image_logo.id as imageId', 'image_logo.providerReference')
            ->where('model.name LIKE :name')
            ->setParameter('name', '%' . $name . '%')
            ->getQuery();

        return $query->getResult();
    }

    /**
     * Search model
     *
     * Get model collection for empty search param
     *
     * @return array
     */
    public function searchModel()
    {
        $query = $this->createQueryBuilder('model')
            ->leftJoin('model.imageLogo', 'image_logo')
            ->select('model.name', 'model.id', 'model.slug')
            ->addSelect('image_logo.id as imageId', 'image_logo.providerReference')
            ->getQuery();

        return $query->getResult();
    }
}
