<?php

namespace CarBundle\Repository;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get models list
     *
     * Get all model list which exists
     *
     * @return mixed
     */
    public function getModelsList()
    {
        $query = $this->createQueryBuilder('m')
            ->orderBy('m.name', 'DESC')
            ->getQuery();

        return $query->execute();
    }


    /**
     * Get model by user id
     *
     * Get model list query by passed user id
     *
     * @param $userId int|null
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getModelsByUserId($userId = null)
    {
        $query = $this->createQueryBuilder('model');

        $query = ($userId) ? $query
            ->join('UserBundle:UserCar', 'user_car', 'WITH', 'model.id = user_car.model')
            ->where('user_car.user =:userId')
            ->setParameter('userId', $userId) : $query;

        $query->orderBy('model.id', 'ASC');

        return $query;
    }

    /**
     * Get model by name
     *
     * Get model item by passed name param
     *
     * @param string $name
     * @return mixed
     */
    public function getModelByName(string $name)
    {
        $query = $this->createQueryBuilder('model')
            ->where('model.name =:name')
            ->setParameter('name', $name)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    /**
     * Get first model
     *
     * Get first model record from model list store
     *
     * @return array
     */
    public function getFirstModel()
    {
        $query = $this->createQueryBuilder('model')
            ->setMaxResults(1)
            ->getQuery();

        return $query->getSingleResult();
    }

    /** Search model
     *
     * Search model record by passed model name param
     *
     * @param string $name
     * @return array
     */
    public function searchModel(string $name)
    {
        $query = $this->createQueryBuilder('model')
            ->leftJoin('model.imageLogo', 'image_logo')
            ->select('model.name', 'model.id', 'model.slug')
            ->addSelect('image_logo.id as imageId', 'image_logo.providerReference')
            ->where('model.name LIKE :name')
            ->setParameter('name', '%' . $name . '%')
            ->getQuery();

        return $query->getResult();
    }
}
