<?php

namespace CarBundle\Repository;

/**
 * TransmissionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransmissionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
