<?php

namespace CarBundle\Repository;

/**
 * TransmissionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransmissionTypeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get item by title
     *
     * Get transmission type item by passed title
     *
     * @param string $title
     * @return mixed
     */
    public function getItemByTitle(string $title)
    {
        $query = $this->createQueryBuilder('transmission_type')
            ->where('transmission_type.title =:title')
            ->setParameter('title', $title)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    /**
     * Get first transmission type
     *
     * Get the first existing transmission type
     *
     * @return mixed
     */
    public function getFirstTransmissionType()
    {
        $query = $this->createQueryBuilder('transmission_type')
            ->setMaxResults(1)
            ->getQuery();

        return $query->getSingleResult();
    }
}
