model_list:
    path:     /model
    defaults: { _controller: CarBundle:Model:index}

model_cars_list:
    path:     /model/{model}
    defaults: { _controller: CarBundle:Model:modelCars}

car_view:
    path:     /models/{model}/{carName}
    defaults: { _controller: CarBundle:Car:view}

car_view_specs:
    path:     /models/{model}/{carName}/specs
    defaults: { _controller: CarBundle:Car:viewSpecs}