services:

    # Model admin service component
    admin.model:
        class: CarBundle\Admin\ModelAdmin
        arguments: [~, CarBundle\Entity\Model, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: CarBundle
              label: 'service.label'
              label_catalogue: ModelBundle

    # TransmissionType admin service component
    admin.trasmission_type:
        class: CarBundle\Admin\TransmissionTypeAdmin
        arguments: [~, CarBundle\Entity\TransmissionType, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: CarBundle
              label: 'TransmissionType'
              label_catalogue: 'TransmissionType'
        public: true

    # Transmission admin service component
    admin.transmission:
        class: CarBundle\Admin\TransmissionAdmin
        arguments: [~, CarBundle\Entity\Transmission, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: CarBundle
              label: 'Transmission'
              label_catalogue: 'Transmission'
        public: true

