services:

    gallery.transformer:
        class: CarBundle\Form\DataTransformer\GalleryToMediaTransformer
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: gallery_transformer }

    form.feature:
        class: CarBundle\Form\FeatureType
        arguments:
            - "@gallery.transformer"
        tags:
            - { name: form.type, alias: form_feature }
    # Model admin service component
    admin.model:
        class: CarBundle\Admin\ModelAdmin
        arguments: [~, CarBundle\Entity\Model, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: CarBundle
              label: 'service.label'
              label_catalogue: ModelBundle

    # Car admin service component
    admin.car:
        class: CarBundle\Admin\CarAdmin
        arguments: [~, CarBundle\Entity\Car, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: CarBundle
              label: 'service.label.car'
              label_catalogue: CarBundle

    # TransmissionType admin service component
    admin.trasmission_type:
        class: CarBundle\Admin\TransmissionTypeAdmin
        arguments: [~, CarBundle\Entity\TransmissionType, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: CarBundle
              label: 'TransmissionType'
              label_catalogue: 'TransmissionType'
        public: true

    # Transmission admin service component
    admin.transmission:
        class: CarBundle\Admin\TransmissionAdmin
        arguments: [~, CarBundle\Entity\Transmission, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: CarBundle
              label: 'Transmission'
              label_catalogue: 'Transmission'
        public: true

    # Engine admin service component
    admin.engine:
        class: CarBundle\Admin\EngineAdmin
        arguments: [~, CarBundle\Entity\Engine, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: CarBundle
              label: 'Engine'
              label_catalogue: 'Engine'
        public: true
