services:
    admin.model:
        class: CarBundle\Admin\ModelAdmin
        arguments: [~, CarBundle\Entity\Model, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: CatBundle
              label: 'service.label'
              label_catalogue: ModelBundle
